[project]
name = "harvardfinal"
version = "0.1.0"
description = "This is my final project for the CS50 programming course."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "reflex>=0.8.3",
]
